# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadTitle', models.CharField(default=b'', max_length=128, unique=True)),
                ('threadSlug', models.SlugField(default=b'', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumThreadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.CharField(default=b'', max_length=128)),
                ('linkedThread', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='FriendsFinder.ForumThread')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionContent', models.CharField(default=b'', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionChoiceValue', models.CharField(default=b'', max_length=128)),
                ('questionChoiceContent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='FriendsFinder.QuizQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to=b'profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
